account/urls.py
from django.urls import path, include
from .views import Register

app_name = 'account'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
]

api/urls.py
from django.urls import path, include
from .views import *


app_name = 'api'

urlpatterns = [
    # http://127.0.0.1:8000/api/v1/coffee-houses/
    path('coffee-houses/', CoffeeHouseAPIList.as_view()),
    path('coffee-houses/<int:pk>/', CoffeeHouseAPIUpdate.as_view()),
    path('coffee-houses/delete/<int:pk>/', CoffeeHouseAPIDestroy.as_view()),
    # http://127.0.0.1:8000/api/v1/menus/
    path('menus/', MenuAPIList.as_view()),
    path('menus/<int:pk>', MenuAPIUpdate.as_view()),
    path('menus/delete/<int:pk>', MenuAPIDestroy.as_view()),
    # http://127.0.0.1:8000/api/v1/menu-items/
    path('menu-items/', MenuItemAPIList.as_view()),
    path('menu-items/<int:pk>', MenuItemAPIUpdate.as_view()),
    path('menu-items/delete/<int:pk>', MenuItemAPIDestroy.as_view()),
]

cafe/urls.py
from django.urls import path
from . import views

app_name = 'cafe'

urlpatterns = [
    # список всех кофеен
    path('', views.coffee_house_list, name='coffee_house_list'),

    # Эндпоинты кофеен - CoffeeHouse
    path('add_coffee_house/', views.coffee_house_add,
         name='coffee_house_add'),  # добавление кофейни
    path('<slug:coffee_house_slug>/',
         views.coffee_house_details, name='coffee_house_details'),  # подробнее о кофейне(меню, позиции)
    path('<slug:coffee_house_slug>/edit/',
         views.coffee_house_edit, name='coffee_house_edit'),  # страница редактирования кофейни
    path('<slug:coffee_house_slug>/delete/',
         views.coffee_house_delete, name='coffee_house_delete'),  # эндпоинт удаления кофейни
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    path('', include('cafe.urls', namespace='cafe')),
    path('<slug:coffee_house_slug>/menu/',
         include('menu.urls', namespace='menu')),

    # api urls
    path('api/v1/', include('api.urls', namespace='api')),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

templates/service/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <!-- outside links -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- inside links -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 my-3 border-bottom">
            <a href="{% url 'cafe:coffee_house_list' %}" class="d-flex align-items-center text-dark text-decoration-none">
                <span class="fs-4">Тестовое задание Климат Холдинг</span>
            </a>
            
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <p>User: {{ user }}</p>
                {% if user.is_authenticated %}
                <a href="{% url 'cafe:coffee_house_add' %}" class="me-3 py-2 text-dark text-decoration-none btn btn-outline-warning">Добавить новую кофейню</a>
                <form action="{% url 'account:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="me-3 py-2 text-dark text-decoration-none btn btn-outline-danger">Log Out</button>
                </form>
                {% else %}
                    <a href="{% url 'account:login' %}" class="me-3 py-2 text-dark text-decoration-none btn btn-outline-success">Login</a>
                    <a href="{% url 'account:register' %}" class="me-3 py-2 text-dark text-decoration-none btn btn-outline-success">Register</a>
                {% endif %}
            </nav>
        </div>
        {% block content %}{% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </div>
</body>
</html>

templates/service/edit.html
{% extends 'service/base.html' %}

{% block title %}
    Редактировать данные
{% endblock %}

{% block content %}
    <h1 class="mb-3 text-center">Редактировать данные</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Редактировать"></p>
    </form>
{% endblock %}