api/urls.py
from django.urls import path, include
from .views import *


app_name = 'api'

urlpatterns = [
    # http://127.0.0.1:8000/api/v1/coffee-houses/
    path('coffee-houses/', CoffeeHouseAPIList.as_view()),
    path('coffee-houses/<int:pk>/', CoffeeHouseAPIUpdate.as_view()),
    path('coffee-houses/delete/<int:pk>/', CoffeeHouseAPIDestroy.as_view()),
    # http://127.0.0.1:8000/api/v1/menus/
    path('menus/', MenuAPIList.as_view()),
    path('menus/<int:pk>', MenuAPIUpdate.as_view()),
    path('menus/delete/<int:pk>', MenuAPIDestroy.as_view()),
    # http://127.0.0.1:8000/api/v1/menu-items/
    path('menu-items/', MenuItemAPIList.as_view()),
    path('menu-items/<int:pk>', MenuItemAPIUpdate.as_view()),
    path('menu-items/delete/<int:pk>', MenuItemAPIDestroy.as_view()),
]

cafe/urls.py
from django.urls import path
from . import views

app_name = 'cafe'

urlpatterns = [
    # список всех кофеен
    path('', views.coffee_house_list, name='coffee_house_list'),

    # Эндпоинты кофеен - CoffeeHouse
    path('add_coffee_house/', views.coffee_house_add,
         name='coffee_house_add'),  # добавление кофейни
    path('<slug:coffee_house_slug>/',
         views.coffee_house_details, name='coffee_house_details'),  # подробнее о кофейне(меню, позиции)
    path('<slug:coffee_house_slug>/edit/',
         views.coffee_house_edit, name='coffee_house_edit'),  # страница редактирования кофейни
    path('<slug:coffee_house_slug>/delete/',
         views.coffee_house_delete, name='coffee_house_delete'),  # эндпоинт удаления кофейни
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    path('', include('cafe.urls', namespace='cafe')),
    path('<slug:coffee_house_slug>/menu/',
         include('menu.urls', namespace='menu')),

    # api urls
    path('api/v1/', include('api.urls', namespace='api')),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    # Эндпоинты меню - Menu
    path('add/', views.menu_add, name='menu_add'),  # добавление меню
    path('<slug:menu_slug>/', views.menu_details,
         name='menu_details'),  # подробнее о меню
    path('<slug:menu_slug>/edit/', views.menu_edit,
         name='menu_edit'),  # редактирование меню
    path('<slug:menu_slug>/delete/', views.menu_delete,
         name='menu_delete'),  # удаление меню

    # Эндпоинты позиций - MenuItems
    path('<slug:menu_slug>/items/add/', views.menu_item_add,
         name='menu_item_add'),  # добавление позиции
    path('<slug:menu_slug>/items/<int:item_id>/', views.menu_item_details,
         name='menu_item_details'),  # подробнее о позиции
    path('<slug:menu_slug>/items/<int:item_id>/edit/', views.menu_item_edit,
         name='menu_item_edit'),  # редактирование позиции
    path('<slug:menu_slug>/items/<int:item_id>/delete/', views.menu_item_delete,
         name='menu_item_delete'),  # удаление позиции
]

cafe/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify


class CoffeeHouse(models.Model):
    """Кофейни"""
    name = models.CharField(max_length=64, unique=True, blank=False)
    slug = models.SlugField(max_length=128, unique=True)
    # Название и слаг уникальные, потому что слаг будет использоваться в ссылках
    work_time = models.CharField(max_length=128, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    user = models.ForeignKey(
        User, verbose_name='Пользователь', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created']

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if self.name:
            self.slug = slugify(self.name)

        super(CoffeeHouse, self).save(*args, **kwargs)

cafe/forms.py
from django import forms
from .models import CoffeeHouse


class CoffeeHouseForm(forms.ModelForm):
    class Meta:
        model = CoffeeHouse
        fields = ['name', 'description', 'work_time']

cafe/views.py
from django.shortcuts import render, redirect
from .models import CoffeeHouse
from .forms import CoffeeHouseForm
from services import queries


def coffee_house_list(request):
    """Список кофеен"""
    coffee_houses = queries.get_all_objects(CoffeeHouse)
    return render(request, 'cafe/list.html',
                  {'coffee_houses': coffee_houses})


def coffee_house_details(request, coffee_house_slug):
    """Подробнее о кофейне"""
    coffee_house = queries.get_object_by_slug(CoffeeHouse, coffee_house_slug)
    # Список меню, которые имеет кофейня
    menu_list = coffee_house.menus.all()
    return render(request, 'cafe/details.html',
                  {'coffee_house': coffee_house,
                   'menu_list': menu_list})


def coffee_house_add(request):
    """Добавить кофейню"""
    if request.method == 'POST':
        form = CoffeeHouseForm(request.POST)
        if form.is_valid():
            coffee_house = form.save()
            coffee_house.save()
            return redirect('cafe:coffee_house_list')
    else:
        form = CoffeeHouseForm()
    return render(request, 'cafe/add.html',
                  {'form': form})


def coffee_house_edit(request, coffee_house_slug):
    """Редактировать кофейню"""
    coffee_house = queries.get_object_by_slug(CoffeeHouse, coffee_house_slug)
    if request.method == 'POST':
        form = CoffeeHouseForm(request.POST, instance=coffee_house)
        if form.is_valid():
            coffee_house = form.save()
            coffee_house.save()
            return redirect('cafe:coffee_house_details', coffee_house_slug=coffee_house.slug)
    else:
        form = CoffeeHouseForm(instance=coffee_house)
    return render(request, 'service/edit.html',
                  {'form': form})


def coffee_house_delete(request, coffee_house_slug):
    queries.delete_object_by_slug(CoffeeHouse, coffee_house_slug)
    return redirect('cafe:coffee_house_list')

templates/cafe/add.html
{% extends 'service/base.html' %}

{% block title %}
    Добавить кофейню
{% endblock %}

{% block content %}
    <h1 class="mb-3 text-center">Добавить кофейню</h1>
    <form action="{% url 'cafe:coffee_house_add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Добавить кофейню"></p>
    </form>
{% endblock %}

templates/cafe/details.html
{% extends 'service/base.html' %}

{% block title %}
    {{ coffee_house.name }}
{% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'cafe:coffee_house_list' %}">Главная</a></li>
      <li class="breadcrumb-item active">{{ coffee_house.name }}</li>
    </ol>
</nav>

<h1 class="mb-3 text-center">{{ coffee_house.name }}</h1>


<div class="alert alert-info" role="alert">
    <h2>{{ coffee_house.name }}</h2>
    <p class="fs-5">Описание: {{ coffee_house.description }}</p>
    <p class="text-body-tertiary">Время работы: {{ coffee_house.work_time }}</p>
    <div class="d-flex flex-row">
        <a class="text-dark btn btn-outline-primary me-2"
        href="{% url 'menu:menu_add' coffee_house_slug=coffee_house.slug %}">Добавить меню</a>
        <a class="text-dark btn btn-outline-warning me-2"
        href="{% url 'cafe:coffee_house_edit' coffee_house_slug=coffee_house.slug %}">Редактировать</a>
        <a class="text-white btn btn-danger" href="{% url 'cafe:coffee_house_delete' coffee_house_slug=coffee_house.slug %}">Удалить</a>
    </div>
</div>

{% if menu_list %}
<h1>Меню:</h1>
    <div class="alert alert-secondary w-50" role="alert">
        <div class="list-group my-2 w-100">
        {% for menu in menu_list %}
            <a class="list-group-item list-group-item-action" aria-current="true"
            href="{% url 'menu:menu_details' coffee_house_slug=coffee_house.slug menu_slug=menu.slug %}">{{ menu.name }}</a>
        {% endfor %}
        </div>
    </div>
{% endif %}

{% endblock %}

templates/cafe/list.html
{% extends 'service/base.html' %}

{% block title %}
    Список кофеен
{% endblock %}

{% block content %}
<h1 class="mb-3 text-center">Список кофеен</h1>

{% for house in coffee_houses %}
<div class="alert alert-info" role="alert">
    <h2>{{ house.name }}</h2>
    <p class="fs-5">{{ house.description }}</p>
    <p class="text-body-tertiary">{{ house.work_time }}</p>
    <div class="d-flex flex-row">
        <a class="text-dark btn btn-outline-warning" href="{% url 'cafe:coffee_house_details' coffee_house_slug=house.slug %}">Подробнее</a>
    </div>
</div>
{% endfor %}
{% endblock %}